"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, ArrowUpRight, Bell, BookOpen, CalendarDays, Check, ChevronDown, CircleHelp, ClipboardList, FilePlus2, FileText, GraduationCap, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, Search, Settings2, Sparkles, Upload, Users, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";

type Section = "overview" | "materials" | "assignments" | "quizzes" | "grades" | "students";
type Item = { title: string; subject: string; group: string; date: string; status: string; kind: string };
const navigation: { id: Section; title: string; icon: LucideIcon }[] = [
  { id: "overview", title: "Dashboard", icon: LayoutDashboard }, { id: "materials", title: "Materi", icon: BookOpen },
  { id: "assignments", title: "Tugas & Project", icon: ClipboardList }, { id: "quizzes", title: "Quiz & Ujian", icon: CircleHelp },
  { id: "grades", title: "Penilaian", icon: Activity }, { id: "students", title: "Data Siswa", icon: Users },
];
const seed: Item[] = [
  { title: "Membangun Halaman Web Responsif", subject: "Pemrograman Web", group: "XII PPLG 1", date: "12 Okt 2026", status: "Aktif", kind: "Tugas" },
  { title: "Dasar-Dasar HTML & Semantic Tag", subject: "Pemrograman Web", group: "XII PPLG 2", date: "14 Okt 2026", status: "Aktif", kind: "Materi" },
  { title: "Quiz CSS Layout dan Flexbox", subject: "Pemrograman Web", group: "XI PPLG 1", date: "10 Okt 2026", status: "Perlu ditinjau", kind: "Quiz" },
  { title: "Proyek Mini: Profil Sekolah", subject: "Pemrograman Web", group: "XII PPLG 1", date: "18 Okt 2026", status: "Aktif", kind: "Project" },
];
const students = ["Aisyah Putri Ramadhani", "Bima Arya Saputra", "Citra Maharani", "Dimas Prasetyo", "Eka Wijaya"];
const teacherStats: { label: string; value: string; sub: string; icon: LucideIcon; bg: string; fg: string; trend: string }[] = [
  { label: "Total Materi", value: "24", sub: "3 materi baru bulan ini", icon: BookOpen, bg: "#e9f1ff", fg: "#3b78e7", trend: "+12%" },
  { label: "Tugas Aktif", value: "8", sub: "4 segera jatuh tempo", icon: ClipboardList, bg: "#fff3e7", fg: "#dc8b37", trend: "+2" },
  { label: "Quiz & Ujian", value: "5", sub: "2 menunggu penilaian", icon: CircleHelp, bg: "#f2edff", fg: "#8262dc", trend: "+1" },
  { label: "Total Siswa", value: "128", sub: "Di 4 kelas berbeda", icon: Users, bg: "#e9f8f1", fg: "#35a878", trend: "+8%" },
];
const titleMap: Record<Section,string> = { overview:"Dashboard", materials:"Materi pembelajaran", assignments:"Tugas & project", quizzes:"Quiz & ujian", grades:"Penilaian", students:"Data siswa" };

export default function TeacherDashboard() {
  const [section,setSection] = useState<Section>("overview");
  const [items,setItems] = useState<Item[]>(seed);
  const [query,setQuery] = useState("");
  const [modal,setModal] = useState<"Materi"|"Tugas"|"Project"|"Quiz"|"Ujian"|null>(null);
  const [notice,setNotice] = useState("");
  const [mobileOpen,setMobileOpen] = useState(false);
  const [authorized,setAuthorized] = useState(false);
  const [name,setName] = useState("Hendra");
  const [today,setToday] = useState("Jadwal hari ini");
  const router=useRouter();
  useEffect(()=>{ if(localStorage.getItem("cittclass_demo_role")!=="guru"){router.replace("/login");return;} const saved=localStorage.getItem("cittclass_demo_name"); if(saved)setName("Hendra"); setToday(new Date().toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"})); setAuthorized(true); },[router]);
  const visible=useMemo(()=>items.filter(item=>`${item.title} ${item.subject} ${item.group}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  const addItem=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const title=String(form.get("title")||"").trim();if(!title)return;setItems(current=>[{title,subject:String(form.get("subject")||"Pemrograman Web"),group:String(form.get("group")||"XII PPLG 1"),date:"20 Okt 2026",status:"Draft",kind:modal??"Materi"},...current]);setNotice(`${modal} berhasil ditambahkan sebagai draft.`);setModal(null);window.setTimeout(()=>setNotice(""),3200);};
  const signOut=()=>{localStorage.removeItem("cittclass_demo_role");localStorage.removeItem("cittclass_demo_name");localStorage.removeItem("cittclass_session_v1");window.location.href="/login";};
  const quickActions:[string,"Materi"|"Tugas"|"Project"|"Quiz"|"Ujian",LucideIcon][]=[["Tambah materi","Materi",FilePlus2],["Buat tugas","Tugas",ClipboardList],["Buat project","Project",GraduationCap],["Buat quiz","Quiz",CircleHelp],["Buat ujian","Ujian",CalendarDays]];
  if(!authorized)return <main className="teacher-loading"><span className="teacher-brand-mark">C</span><p>Menyiapkan ruang guru…</p></main>;
  return <div className="teacher-app">
    {mobileOpen&&<button className="teacher-scrim" onClick={()=>setMobileOpen(false)} aria-label="Tutup menu"/>}
    <aside className={`teacher-sidebar${mobileOpen?" mobile-open":""}`}><Link href="/" className="teacher-brand"><span className="teacher-brand-mark">C</span><span>Citt<span>Class</span><small>RUANG GURU</small></span></Link><span className="teacher-nav-label">MENU UTAMA</span><nav className="teacher-nav">{navigation.map(({id,title,icon:Icon})=><button key={id} className={section===id?"active":""} onClick={()=>{setSection(id);setMobileOpen(false);}}><Icon size={18}/><span>{title}</span>{id==="assignments"&&<i>3</i>}</button>)}</nav><div className="teacher-side-bottom"><div className="teacher-help"><span><CircleHelp size={18}/></span><b>Butuh bantuan?</b><small>Hubungi admin sekolah untuk bantuan akun.</small></div><button className="teacher-logout" onClick={signOut}><LogOut size={17}/>Keluar dari akun</button></div></aside>
    <main className="teacher-main"><header className="teacher-topbar"><div className="teacher-top-left"><button className="teacher-menu-button" aria-label="Buka menu" onClick={()=>setMobileOpen(true)}><Menu size={20}/></button><div className="teacher-breadcrumb">Portal Guru <span>/</span> {titleMap[section]}</div></div><div className="teacher-top-actions"><span className="teacher-school-pill"><span/>Tahun Ajaran 2026/2027 <ChevronDown size={14}/></span><button className="teacher-icon-button" aria-label="Cari" onClick={()=>document.getElementById("teacher-search")?.focus()}><Search size={18}/></button><button className="teacher-icon-button notification-button" aria-label="Notifikasi"><Bell size={18}/><i/></button><div className="teacher-profile"><span className="teacher-avatar">HG</span><span><b>Hendra Gunawan</b><small>Guru · Pemrograman Web</small></span><ChevronDown size={14}/></div></div></header>
      <div className="teacher-content"><div className="teacher-page-heading"><div><span className="teacher-date"><CalendarDays size={14}/> {today}</span><h1>{section==="overview"?<>Selamat pagi, {name} <span>✦</span></>:titleMap[section]}</h1><p>{section==="overview"?"Siap melanjutkan kegiatan belajar hari ini? Ini ringkasan kelasmu.":`Kelola dan pantau ${titleMap[section].toLowerCase()} untuk kelas yang kamu ampu.`}</p></div>{section!=="overview"&&section!=="students"&&<button className="t-button t-primary" onClick={section==="grades"?()=>setNotice("Pratinjau generate nilai dibuka. Bobot penilaian dapat disesuaikan sebelum terhubung ke backend."):()=>setModal(section==="materials"?"Materi":section==="assignments"?"Tugas":"Quiz")}><Plus size={17}/>{section==="grades"?"Generate nilai":section==="materials"?"Tambah materi":section==="assignments"?"Buat tugas":"Buat quiz"}</button>}</div>
      {notice&&<div className="teacher-toast"><Check size={16}/>{notice}<button onClick={()=>setNotice("")} aria-label="Tutup"><X size={15}/></button></div>}
      {section==="overview"?<>
        <div className="teacher-stats">{teacherStats.map(({label,value,sub,icon:Icon,bg,fg,trend})=><article className="teacher-stat" key={label}><div className="stat-top"><span>{label}</span><i style={{background:bg,color:fg}}><Icon size={18}/></i></div><div className="stat-value">{value}<small>{trend}</small></div><p>{sub}</p></article>)}</div>
        <div className="teacher-dashboard-grid"><section className="teacher-panel activity-panel"><div className="panel-heading"><div><h2>Aktivitas pembelajaran</h2><p>Ringkasan aktivitas dalam 7 hari terakhir</p></div><button className="period-select">7 hari terakhir <ChevronDown size={14}/></button></div><div className="chart-legend"><span><i/>Materi dipelajari</span><span><i/>Tugas dikumpulkan</span></div><div className="bar-chart"><div className="chart-y-axis"><span>40</span><span>30</span><span>20</span><span>10</span><span>0</span></div><div className="chart-bars">{[["Sen",55,33],["Sel",72,48],["Rab",42,61],["Kam",82,56],["Jum",63,36],["Sab",34,22],["Min",49,29]].map(([day,a,b])=><div className="chart-column" key={String(day)}><div className="bar-pair"><i style={{height:`${a}%`}}/><i style={{height:`${b}%`}}/></div><small>{day}</small></div>)}</div></div><div className="chart-foot"><span><ArrowUpRight size={15}/> Aktivitas naik <b>12,8%</b> dibanding minggu lalu</span><button onClick={()=>setSection("grades")}>Lihat laporan <ArrowRight size={14}/></button></div></section>
          <section className="teacher-panel class-panel"><div className="panel-heading"><div><h2>Kelas yang diampu</h2><p>Progres siswa per kelas</p></div><button className="more-button" aria-label="Opsi lainnya"><MoreHorizontal size={19}/></button></div><div className="class-list">{[["XII PPLG 1","32 siswa",78,"blue"],["XII PPLG 2","30 siswa",64,"purple"],["XI PPLG 1","34 siswa",86,"green"],["XI PPLG 2","32 siswa",52,"orange"]].map(([cls,count,progress,color])=><div className="class-row" key={String(cls)}><span className={`class-icon ${color}`}><GraduationCap size={17}/></span><div className="class-info"><div><b>{cls}</b><small>{count}</small></div><div className="class-progress"><i className={String(color)} style={{width:`${progress}%`}}/></div></div><strong>{progress}%</strong></div>)}</div><button className="panel-link" onClick={()=>setSection("students")}>Lihat data siswa <ArrowRight size={15}/></button></section></div>
        <section className="teacher-panel work-panel"><div className="panel-heading"><div><h2>Aktivitas terbaru</h2><p>Materi, tugas, dan quiz yang kamu kelola</p></div><button className="panel-link" onClick={()=>setSection("assignments")}>Lihat semua <ArrowRight size={15}/></button></div><ActivityTable items={items.slice(0,4)}/></section>
        <section className="quick-section"><div className="quick-heading"><div><h2>Mulai sesuatu yang baru</h2><p>Akses cepat untuk menyiapkan kegiatan belajar.</p></div><Sparkles size={19}/></div><div className="quick-grid">{quickActions.map(([label,kind,Icon])=><button key={label} className="quick-action" onClick={()=>setModal(kind)}><span><Icon size={18}/></span><b>{label}</b><ArrowRight size={15}/></button>)}<button className="quick-action" onClick={()=>setSection("grades")}><span><Activity size={18}/></span><b>Generate nilai</b><ArrowRight size={15}/></button></div></section>
      </>:section==="students"?<section className="teacher-panel work-panel"><div className="panel-heading"><div><h2>Daftar siswa</h2><p>Hanya siswa dari kelas yang kamu ampu yang ditampilkan.</p></div><select className="period-select" aria-label="Pilih kelas"><option>Semua kelas</option><option>XII PPLG 1</option><option>XII PPLG 2</option></select></div><div className="student-grid">{students.map((student,i)=><article className="student-card" key={student}><span className="student-avatar">{student.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><b>{student}</b><small>{["XII PPLG 1","XII PPLG 2","XI PPLG 1","XII PPLG 1","XI PPLG 2"][i]} · NIS {2210001+i}</small></div><span className="status-chip status-green">Aktif</span></article>)}</div></section>:<section className="teacher-panel work-panel"><div className="panel-heading"><div><h2>{titleMap[section]}</h2><p>Daftar konten pembelajaran untuk kelasmu.</p></div><div className="table-tools"><label className="teacher-search"><Search size={16}/><input id="teacher-search" placeholder="Cari aktivitas..." value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="period-select"><Settings2 size={15}/> Filter</button></div></div><ActivityTable items={visible.filter(item=>section==="materials"?item.kind==="Materi":section==="assignments"?item.kind==="Tugas"||item.kind==="Project":section==="quizzes"?item.kind==="Quiz":true)}/></section>}
      </div><footer className="teacher-footer"><span>© 2026 CittClass</span><span>Ruang belajar, tumbuh bersama.</span><button><CircleHelp size={14}/> Pusat bantuan</button></footer>
    </main>
    {modal&&<div className="teacher-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null);}}><form className="teacher-modal" onSubmit={addItem}><div className="modal-head"><div><span className="eyebrow">KEGIATAN PEMBELAJARAN</span><h2>Buat {modal.toLowerCase()}</h2></div><button type="button" className="modal-close" onClick={()=>setModal(null)} aria-label="Tutup"><X size={19}/></button></div><label>Judul {modal.toLowerCase()}<input name="title" placeholder={`Contoh: ${modal} Pemrograman Web`} required autoFocus/></label><label>Mata pelajaran<select name="subject"><option>Pemrograman Web</option><option>Basis Data</option><option>Desain Antarmuka</option></select></label><label>Kelas<select name="group"><option>XII PPLG 1</option><option>XII PPLG 2</option><option>XI PPLG 1</option><option>XI PPLG 2</option></select></label><div className="upload-box"><Upload size={18}/><span><b>Tambahkan lampiran</b><small>PDF, PPTX atau video · maks. 20 MB</small></span><input type="file" aria-label="Pilih lampiran"/></div><div className="modal-actions"><button type="button" className="t-button t-outline" onClick={()=>setModal(null)}>Batal</button><button type="submit" className="t-button t-primary"><Check size={16}/>Simpan draft</button></div><p className="modal-hint"><FileText size={14}/> Draft ini hanya tersimpan di pratinjau frontend.</p></form></div>}
  </div>;
}

function ActivityTable({items}:{items:Item[]}) { return <div className="activity-table-wrap"><table className="activity-table"><thead><tr><th>AKTIVITAS</th><th>MATA PELAJARAN</th><th>KELAS</th><th>TANGGAL / DEADLINE</th><th>STATUS</th><th/></tr></thead><tbody>{items.length?items.map((item,i)=><tr key={`${item.title}-${i}`}><td><span className={`activity-type type-${item.kind.toLowerCase()}`}>{item.kind==="Materi"?<BookOpen size={16}/>:item.kind==="Tugas"||item.kind==="Project"?<ClipboardList size={16}/>:<CircleHelp size={16}/>}</span><b>{item.title}</b></td><td>{item.subject}</td><td>{item.group}</td><td>{item.date}</td><td><span className={`status-chip ${item.status==="Aktif"?"status-green":item.status==="Draft"?"status-gray":"status-amber"}`}><i/>{item.status}</span></td><td><button className="more-button" aria-label={`Opsi ${item.title}`}><MoreHorizontal size={18}/></button></td></tr>):<tr><td colSpan={6} className="table-empty"><span><FileText size={22}/></span><b>Belum ada data</b><small>Aktivitas yang sesuai pencarian belum tersedia.</small></td></tr>}</tbody></table></div>; }
